# This Conda environment facilitates package management and ensures reproducibility.
#
# It sets up a virtual environment with specified dependencies and versions,
# making it easier to run commands via a Makefile for a consistent development and execution environment.

name: electric-brew
channels:
  - conda-forge

dependencies:
  - cycler       # For color cycling in `plt_params` using cycler()
  - make         # For build automation using Makefile
  - matplotlib   # For plotting with plt.hist(), plt.plot(), plt.savefig(), etc.
  - numpy        # Used for numerical operations like sqrt() and linspace()
  - pandas       # For data manipulation and analysis using DataFrames
  - pdfplumber   # For parsing PDF files and extracting text from them
  - pyarrow      # For curating data into `.parquet` structures with compression and logical partitioning
  - scipy        # For scientific computing, specifically norm.pdf() and norm.fit() in scipy.stats
  - seaborn      # For advanced plotting of linear regressions
